basePath: /
definitions:
  handler.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.RegisterRequest:
    properties:
      password:
        type: string
      role:
        enum:
        - admin
        - employee
        type: string
      username:
        type: string
    required:
    - password
    - role
    - username
    type: object
  helper.Pagination:
    properties:
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  helper.PaginationResponse:
    properties:
      data: {}
      message:
        type: string
      meta:
        $ref: '#/definitions/helper.Pagination'
      success:
        type: boolean
    type: object
  helper.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  service.ProductRequest:
    properties:
      category:
        enum:
        - rice
        - bran
        type: string
      description:
        type: string
      name:
        type: string
      photo:
        type: string
      price:
        type: number
      stock:
        type: number
      unit:
        type: string
    required:
    - category
    - name
    - unit
    type: object
  service.UpdateProfileRequest:
    properties:
      address:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      photo:
        type: string
      status:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for PG Pritani dashboard
  title: PG Pritani API
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user dengan username dan password
      parameters:
      - description: Login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register user baru
      parameters:
      - description: Register data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Register
      tags:
      - Auth
  /customers/:
    get:
      consumes:
      - application/json
      description: get all customer data
      parameters:
      - description: Halaman
        in: query
        name: page
        type: integer
      - description: Limit data
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.PaginationResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Get customer data
      tags:
      - Customers
  /products/:
    get:
      consumes:
      - application/json
      description: Mengambil semua data produk dengan pagination
      parameters:
      - description: Halaman
        in: query
        name: page
        type: integer
      - description: Limit data
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.PaginationResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: List semua produk
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Membuat produk baru
      parameters:
      - description: Product data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Buat produk baru
      tags:
      - Products
  /profile:
    get:
      description: Ambil data profile user yang sedang login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Get Profile
      tags:
      - Auth
    patch:
      consumes:
      - application/json
      description: Update data profile user yang sedang login
      parameters:
      - description: Update data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - BearerAuth: []
      summary: Update Profile
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: Header
    name: Authorization
    type: apiKey
swagger: "2.0"
